import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { ChatGroq } from "@langchain/groq";
import { z } from "zod";
import type {
  EndpointWindowStats,
  MonitorResult
} from "@/modules/monitoring/domain/MonitorContracts";
import { monitorResultSchema } from "@/modules/monitoring/domain/MonitorSchema";

const llmPayloadSchema = z.object({
  window: z.object({
    from: z.string(),
    to: z.string()
  }),
  endpoints: z.array(
    z.object({
      endpoint: z.string(),
      requestCount: z.number(),
      errorRate: z.number(),
      avgResponseTimeMs: z.number(),
      p95LatencyMs: z.number(),
      topErrors: z.array(z.string()),
      slaBreached: z.boolean()
    })
  )
});

const outputContract = `Return ONLY valid JSON in this format:
{
  "timestamp": "",
  "endpoints": [
    {
      "endpoint": "",
      "risk_level": "LOW | MEDIUM | HIGH",
      "sla_breach_predicted": true,
      "reason": "",
      "recommended_action": ""
    }
  ],
  "incident_summary": "",
  "alerts": [
    {
      "endpoint": "",
      "message": "",
      "severity": "info | warning | critical"
    }
  ]
}`;

function fallbackResult(windowTo: string, summaries: EndpointWindowStats[]): MonitorResult {
  return {
    timestamp: windowTo,
    endpoints: summaries.map((item) => ({
      endpoint: item.endpoint,
      risk_level: item.slaBreached ? "HIGH" : item.errorRate > 2 || item.avgResponseTimeMs > 600 ? "MEDIUM" : "LOW",
      sla_breach_predicted: item.slaBreached,
      reason: item.slaBreached
        ? "Deterministic thresholds indicate likely SLA breach in recent window."
        : "Current metrics remain within expected SLA bounds.",
      recommended_action: item.slaBreached
        ? "Scale service, inspect error logs, and enable immediate endpoint alerting."
        : "Continue monitoring and keep existing alert thresholds."
    })),
    incident_summary: "Fallback summary generated by deterministic monitor logic.",
    alerts: summaries
      .filter((item) => item.slaBreached)
      .map((item) => ({
        endpoint: item.endpoint,
        message: `Potential SLA breach predicted for ${item.endpoint}.`,
        severity: "critical" as const
      }))
  };
}

function extractJsonObject(text: string): string {
  const first = text.indexOf("{");
  const last = text.lastIndexOf("}");
  if (first === -1 || last === -1 || first >= last) {
    return text.trim();
  }
  return text.slice(first, last + 1);
}

export async function generateMonitorLlmResult(input: {
  windowFrom: string;
  windowTo: string;
  summaries: EndpointWindowStats[];
}): Promise<MonitorResult> {
  const payload = llmPayloadSchema.parse({
    window: {
      from: input.windowFrom,
      to: input.windowTo
    },
    endpoints: input.summaries
  });

  if (!process.env.GROQ_API_KEY || !process.env.MODEL_NAME) {
    return fallbackResult(input.windowTo, input.summaries);
  }

  const model = new ChatGroq({
    apiKey: process.env.GROQ_API_KEY,
    model: process.env.MODEL_NAME,
    temperature: 0
  });

  try {
    const response = await model.invoke([
      new SystemMessage(
        "You are an SRE monitoring assistant. Use the provided endpoint stats and produce SLA risk insights. " +
          outputContract
      ),
      new HumanMessage(
        `Monitoring window data:\n${JSON.stringify(payload, null, 2)}\n\nReturn JSON only, no markdown, no additional text.`
      )
    ]);
    const parsed = JSON.parse(extractJsonObject(response.text)) as unknown;
    return monitorResultSchema.parse(parsed);
  } catch {
    return fallbackResult(input.windowTo, input.summaries);
  }
}
